name: Update Pi-hole Blocklist

on:
  #schedule:
  #  - cron: '0 0 * * *'   # Daily at midnight UTC
  workflow_dispatch:      # Manual trigger

concurrency:
  group: update-blocklist
  cancel-in-progress: false

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Run sanitizer List 1
        run: |
          cd list1/
          chmod +x sanitize_and_commit.sh
          ./sanitize_and_commit.sh

      - name: Run sanitizer List 2
        run: |
          cd list2/
          chmod +x sanitize_and_commit.sh
          ./sanitize_and_commit.sh

      - name: Run sanitizer (root)
        run: |
          chmod +x sanitize_and_commit.sh
          ./sanitize_and_commit.sh

      - name: Build allowlist
        run: |
          chmod +x build_allowlist.sh
          ./build_allowlist.sh


      - name: Remove intermediate list files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git rm -f list1/blocklist.txt list2/blocklist.txt
          git commit -m "Remove intermediate list files (already merged into root blocklist)" || echo "No changes to commit"
          git push

